IndustryFinder/urls.py
from . import views
from django.conf.urls import url

app_name = 'IndustryFinder'

urlpatterns = [

    #/signup/
    url(r'^signup/$', views.UserFormView.as_view(), name = 'signup'),

    # /profile/<pk>/
    url(r'^profile/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /profile/update/
    url(r'^profile/update/$', views.StudentUpdate, name='student-update'),

    # /profile/
    url(r'^profile/$', views.saveStudentData, name='save-student-data'),

    #/home/
    url(r'^home/$', views.Home.as_view(), name='home'),
]

Vcet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'IndustryFinder/', include('IndustryFinder.urls')),
    path(r'IndustryFinder/', include('django.contrib.auth.urls')),
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    #path('', , name='home'),
]

IndustryFinder/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import jsonfield

#User.Student_set.all.0

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)    
    academics = jsonfield.JSONField()
    sports = jsonfield.JSONField()
    technical = jsonfield.JSONField()
    social = models.IntegerField()
    
    def get_absolute_url(self):
        return reverse('IndustryFinder:details',kwargs={'pk': self.pk})
    #def get_success_url(self):
     #   return reverse('IndustryFinder:details', kwargs={'pk': self.pk})
    def __str__(self):
        return str(self.user.username) + " " + str(self.pk)

IndustryFinder/forms.py
from django.contrib.auth.models import User
#from django.utils.translation import gettext_lazy as _
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password'] 

IndustryFinder/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import login, authenticate
from django.views.generic.edit import UpdateView
from .models import Student
from .forms import UserForm
import pickle
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import json
# Create your views here.

dbfile = open('IndustryFinder/Classifier.pickle', 'rb')
Classifier = pickle.load(dbfile)
dbfile.close()
dbfile2 = open('IndustryFinder/Scaler.pickle', 'rb')
Scaler = pickle.load(dbfile2)
dbfile2.close()

df = pd.read_csv('IndustryFinder/abc.csv', names = [
    'Marks_10',
    'Marks_12',
    'Marks_CGPA',
    'Hackathons',
    'Research',
    'Internship',
    'Projects',
    'Social_hours',
    'Sports',
    'Company'
])

def equivalent(sports):
    National = 3
    State = 2
    Regional = 1
    gold = 3
    silver = 2
    bronze = 1
    sports['Equivalent'] = int(
        National * ( gold * sports['N_Gold'] + silver * sports['N_Silver'] + bronze * sports['N_Bronze'] )
        + State * ( gold * sports['S_Gold'] + silver * sports['S_Silver'] + bronze * sports['S_Bronze'] )
        + Regional * ( gold * sports['R_Gold'] + silver * sports['R_Silver'] + bronze * sports['R_Bronze'] )
    )
def percentilefinder(data, datalist):
    j = 0
    for i in datalist:
        if( data >= datalist[i]):
            j = j + 1
    return j/len(datalist)

class Home(generic.base.TemplateView):
    template_name='home.html'
    def get(self,request):
        try:
            s = request.user.student
            company = Classifier.predict(Scaler.transform(
            [[
            s.academics['Marks_10'],
            s.academics['Marks_12'],
            s.academics['Marks_CGPA'],
            s.technical['Hackathons'],
            s.technical['Research'],
            s.technical['Internships'],
            s.technical['Projects'],
            s.social,
            s.sports['Equivalent'],
            ]]
            ))

            df2 = df[df['Company'] == company[0]]
            meandf2 = df2[['Marks_CGPA','Sports','Social_hours','Research']].mean().tolist()
            maxdf2 = df2[['Marks_CGPA','Sports','Social_hours','Research']].max().tolist()
            scatter = df2[['Marks_10','Marks_12','Hackathons','Internship','Projects']].T.values.tolist()
            a = {
                'company':company[0],
                'meandf2':meandf2,
                'maxdf2':maxdf2,
                'scatter':scatter,
            }
            s = request.user.student
            b = [
                s.academics['Marks_10'],
                s.academics['Marks_12'],
                s.academics['Marks_CGPA'],
                s.technical['Hackathons'],
                s.technical['Research'],
                s.technical['Internships'],
                s.technical['Projects'],
                s.social,
                s.sports['Equivalent'],
            ]

    #        percentile = [
    #           (percentilefinder(s.academics['Marks_10'],df2['Marks_10']) + 
    #          percentilefinder(s.academics.['Marks_12'],df2['Marks_12']))/2,
    #         percentilefinder(s.sports['Equivalent'], df2['Sports']),
        #        percentilefinder(s.technical.Hackathons,df2['Hackathons']) +
        #       percentilefinder(s.technical.Research,df2['Research']) +
        #      percentilefinder(s.technical.Internships,df2['Internship']),
        #     percentilefinder(s.social, df2['Social_hours']),
            #]

            return render(request,self.template_name,{'b':a,'a':b,'student':request.user.student})
        except:
            return redirect('IndustryFinder:student-update')

def StudentUpdate(request):
    try:
        return render(request, r'IndustryFinder/student_form.html', {'student':request.user.student})
    except:
        return redirect('login')

def saveStudentData(request):
    if request.method == "POST":
        s = request.user.student
        academics = {
            "Marks_10": int(int(request.POST["Marks_10"]) / int(request.POST["Marks_10_max"]) * 500),
            "Marks_12": int(int(request.POST["Marks_12"]) / int(request.POST["Marks_12_max"]) * 650),
            "Marks_CGPA": float(request.POST["Marks_CGPA"]),
        }
        technical = {
            "Hackathons": int(request.POST["Hackathons"]),
            "Research": int(request.POST["Research"]),
            "Projects": int(request.POST["Projects"]),
            "Internships": int(request.POST["Internships"]),
        }
        sports = {
            "N_Gold": int(request.POST["N_Gold"]),
            "S_Gold": int(request.POST["S_Gold"]),
            "R_Gold": int(request.POST["R_Gold"]),
            "N_Silver": int(request.POST["N_Silver"]),
            "S_Silver": int(request.POST["S_Silver"]),
            "R_Silver": int(request.POST["R_Silver"]),
            "N_Bronze": int(request.POST["N_Bronze"]),
            "S_Bronze": int(request.POST["S_Bronze"]),
            "R_Bronze": int(request.POST["R_Bronze"]),
        }
        equivalent(sports)
        s.academics = academics
        s.sports = sports
        s.technical = technical
        s.social = int(request.POST["Social_Hours"])
        s.save()
    return redirect('IndustryFinder:home')

class DetailView(generic.DetailView):
    model = Student
    template_name = r'IndustryFinder/student_detail.html'

class UserFormView(generic.View):
    form_class = UserForm
    template_name = r'IndustryFinder/signup_form.html'
    
    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            #cleaned-normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            student = Student()
            student.user = user
            student.social = 0
            student.save()
            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('IndustryFinder:student-update')
                    
        return render(request, self.template_name, {'form' : form})

IndustryFinder/templates/IndustryFinder/form-template.html
{% for field in form %}
	<span> {{ field.errors }} </span>
	<label>{{ field.label_tag }}</label>
	{{ field }}
	</br>
{% endfor %}

IndustryFinder/templates/IndustryFinder/login_form.html
<head>
	<title> Login | IndustryFinder </title>
</head>

<body>
	<div class='panel-body'>
		<form action="" method="post" enctype = "multipart/form-data" >
			{% csrf_token %}
			{% include 'IndustryFinder/form-template.html' %}
			<button type='submit' >Submit!</button>
		</form>
	</div>
</body>

IndustryFinder/templates/IndustryFinder/signup_form.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'IndustryFinder/signup.css' %}" />
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Signup | IndustryFinder</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="login-card">
        <div class="account">
            <h2 class="title">Create Account</h2>
            <div class="body ">
				<form class="login_form" action="" method="post" enctype = "multipart/form-data">
					{% csrf_token %}
                    <div class="form-group">
						<label for="usr">{{ form.username.label_tag }}</label>
                        <input type="text" name="username" class="form-control" id="id_username" maxlength="150"><br>
                    </div>
                    <div class="form-group">
						<label for="pwd">{{ form.password.label_tag }}</label>
                        <input type="password" name="password" class="form-control" id="pwd"><br>
                    </div>
                    <button type="submit" class="btn btn-primary">SIGN UP</button>
                </form>
             </div>
        </div>
        <div class="image">
            <div>
                <span class="alredy-acc">Already have an account?</span>
                <span><button type="submit" class="btn info"><a class="Nolink" href="{% url 'login' %}">LOG IN</a></button></span>
            </div>
            <img class="login_img" src="{% static 'IndustryFinder/undraw_predictive_analytics_kf9n (2).svg' %}" alt="Login Image">
        </div>
    </div>
</body>
</html>

IndustryFinder/templates/IndustryFinder/student_detail.html
<h1>{{ student.pk }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

IndustryFinder/templates/IndustryFinder/student_form.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'IndustryFinder/student_form.css' %}" />
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="main.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Profile</title>
</head>
<body>
    <a href="{% url 'IndustryFinder:home' %}"><button>Back to Home</button><a>
    <form action="{% url 'IndustryFinder:save-student-data' %}" method="post" enctype = "multipart/form-data">
	{% csrf_token %}
    <div class="academics_details card academics_card">
        <div class="container">
            <div class="academics_icon"><i class="fa fa-university"></i></div>
        </div>
        <h2 class="card-title">Academics</h2>
        <hr>
        <div class="card-body">
            <div class="flex-container">
            <div class="form-group left">
                <label for="mOS">Marks obtained in 10th:</label>
                <input required type = "text" value = '{{ student.academics.Marks_10 }}' name = "Marks_10" class="form-control" id = "mOS" />
            </div>
            <div class="form-group right">
                <label for="mMS">Max. marks of 10th:</label>
                <input required type = "text" value = '500' name = "Marks_10_max" class="form-control" id = "mMS" />
            </div>
            </div>
            <div class="flex-container">
                <div class="form-group left">
                    <label for="mOH">Marks obtained in 12th:</label>
                    <input required type = "text" value = '{{ student.academics.Marks_12 }}' name = "Marks_12" class="form-control" id = "mOH" />
                </div>
                <div class="form-group right">
                    <label for="mMH">Max. marks of 12th:</label>
                    <input required type = "text" value = '650' name = "Marks_12_max" class="form-control" id = "mMH" />
                </div>
            </div>
            <div class="flex-container">
                <div class="form-group mid">
                    <label for="cGPA">Avg CGPA obtained:</label>
                    <input required type = "text" value = '{{ student.academics.Marks_CGPA }}' name = "Marks_CGPA" class="form-control" id = "cGPA" />
                </div>
            </div>
        </div>
    </div>
    <div class="sports_details card sports_card">
        <div class="container">
            <div class="sports_icon "><i class="fa fa-futbol-o"></i></div>
        </div>
        <h2 class="card-title">Sports</h2>
        <hr>
        <div class="card-body">
            <div class="regional">
                <h4>Regional</h4>
                <hr>
                <div class="flex-container">
                    <div class="form-group">
                        <label for="nORG">No. of Regional Golds:</label>
                        <input required type = "number" class="form-control" id = "nORG" value = '{{ student.sports.R_Gold }}' name = "R_Gold"/>
                    </div>
                    <div class="form-group">
                        <label for="nORS">No. of Regional Silver:</label>
                        <input required type = "number" class="form-control" id = "nORS" value = '{{ student.sports.R_Silver }}' name = "R_Silver"/>
                    </div>
                    <div class="form-group">
                        <label for="nORB">No. of Regional Bronze:</label>
                        <input required type = "number" class="form-control" id = "nORB" value = '{{ student.sports.R_Bronze }}' name = "R_Bronze"/>
                    </div>
                </div>
            </div>
            <div class="state">
                <hr>
                <h4>State</h4>
                <hr>
                <div class="flex-container">
                    <div class="form-group">
                        <label for="nOSG">No. of State Golds:</label>
                        <input required type = "number" class="form-control" id = "nOSG" value = '{{ student.sports.S_Gold }}' name = "S_Gold"/>
                    </div>
                    <div class="form-group">
                        <label for="nOSS">No. of State Silvers:</label>
                        <input required type = "number" class="form-control" id = "nOSS" value = '{{ student.sports.S_Silver }}' name = "S_Silver"/>
                    </div>
                    <div class="form-group">
                        <label for="nOSB">No. of State Bronzes:</label>
                        <input required type = "number" class="form-control" id = "nOSB" value = '{{ student.sports.S_Bronze }}' name = "S_Bronze"/>
                    </div>
                </div>
            </div>
                <div class="national">
                    <hr>
                    <h4>National</h4>
                    <hr>
                    <div class="flex-container">
                        <div class="form-group">
                            <label for="nONG">No. of National Golds:</label>
                            <input required type = "number" class="form-control" id = "nONG" value = '{{ student.sports.N_Gold }}' name = "N_Gold"/>
                        </div>
                        <div class="form-group">
                            <label for="nONS">No. of National Silver:</label>
                            <input required type = "number" class="form-control" id = "nONS" value = '{{ student.sports.N_Silver }}' name = "N_Silver"/>
                        </div>
                        <div class="form-group">
                            <label for="nONB">No. of National Bronze:</label>
                            <input required type = "number" class="form-control" id = "nONB" value = '{{ student.sports.N_Bronze }}' name = "N_Bronze"/>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <div class="technical_details card technical_card">
        <div class="container">
            <div class="technical_icon"><i class="fa fa-code"></i></div>
        </div>
        <h2 class="card-title">Technical</h2>
        <hr>
        <div class="card-body">
            <div class="flex-container">
                <div class="form-group left">
                    <label for="nOH">No. of Hackathons:</label>
                    <input required type = "number" name = "Hackathons" class="form-control" id = "nOH" value = '{{ student.technical.Hackathons }}'/>
                </div>
                <div class="form-group right">
                        <label for="nORP">No. of Research Papers:</label>
                        <input required type = "number" name = "Research" class="form-control" id = "nORP" value = '{{ student.technical.Research }}'/>
                </div>
            </div>
            <div class="flex-container">
                <div class="form-group left">
                        <label for="nOP">No. of Projects:</label>
                        <input required type = "number" name = "Projects" class="form-control" id = "nOP" value = '{{ student.technical.Projects }}'/>
                </div>
                <div class="form-group right">
                        <label for="nOI">No. of Internships:</label>
                        <input required type = "number" name = "Internships" class="form-control" id = "nOI" value = '{{ student.technical.Internships }}'/>
                </div>
            </div>
        </div>
    </div>
    <div class="social_details card social_card">
        <div class="container">
            <div class="social_icon"><i class="fa fa-tree"></i></div>
        </div>
        <h2 class="card-title">Social</h2>
        <hr>
        <div class="flex-container">
            <div class="form-group mid">
                    <label for="nOSH">No. of Social Hours:</label>
                    <input required type = "text" value = '{{ student.social }}' name = "Social_Hours" class="form-control" id = "nOSH" />
            </div>
        </div>
    </div>
    <button type="submit" class="submit-btn">Submit</button>
</form>
</body>
</html>

templates/home.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'IndustryFinder/home.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'IndustryFinder/circle.css' %}" />
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500&display=swap" rel="stylesheet">
    <title>Student Management System</title>
</head>
<body>
    <main class="grid-container" >
        <section class="nav">
            <div class="vertical-menu">
                <div class="menu-container">
                    <a href="{% url 'IndustryFinder:student-update' %}"><img src="{% static 'IndustryFinder/undraw_profile_pic_ic5t (1).svg' %}" alt=""></a>
                    <a href="#home-point" ><i id="home"  class="fa fa-home active"></i></a>
                    <a href="#academics-point"  ><i id="academics" class="fa fa-university"></i></a>
                    <a href="#sports-point"  ><i id="sports" class="fa fa-futbol-o "></i></a>
                    <a href="#technical-point"  ><i id="technical" class="fa fa-code"></i></a>
                    <a href="#social-point"  ><i id="social" class="fa fa-tree"></i></a>
                </div>
            </div>
        </section>
        <section class="home-container">
            <div class="edit" id="home-point">
                <div class="card" id="comp">
                    <h2>You have a good chance to get placed in {{ b.company }}</h2>
                </div>
                <a href="{% url 'IndustryFinder:student-update' %}"> <button>Edit Profile</button> </a>
                <a href="{% url 'logout' %}"><button>Log out</button></a> 
            </div>
            <div class="flex-container" id="home">
                    <div class="card academics_numeric">
                            <div class="container">
                            <div class="academics_icon icon rounded-circle"><i class="fa fa-university"></i></div>
                            </div>
                            <div class="card-body"><h1 class="data_numeric">92%</h1></div>
                            <h4 class="card-title">Academics</h4>
                        </div>
                        <div class="card sports_numeric">
                            <div class="container">
                            <div class="sports_icon icon "><i class="fa fa-futbol-o"></i></div>
                            </div>
                            <div class="card-body"><h1 class="data_numeric">65%</h1></div>
                            <h4 class="card-title">Sports</h4>
                        </div>
                        <div class="card technical_numeric">
                            <div class="container">
                            <div class="technical_icon icon"><i class="fa fa-code"></i></div>
                            </div>
                            <div class="card-body"><h1 class="data_numeric">86%</h1></div>
                            <h4 class="card-title">Technical</h4>
                        </div>
                        <div class="card social_numeric">
                            <div class="container">
                            <div class="social_icon icon"><i class="fa fa-tree"></i></div>
                            </div>
                            <div class="card-body"><h1 class="data_numeric">72%</h1></div>
                            <h4 class="card-title">Social</h4>
                        </div>
            </div>
            <div class="section-grid-container">
                <div class="Academics sub-container" id="academics-point" >
                    <div class="card">
                        <h4 class="card-title">Scatter Plot of 10th and 12marks</h4>
                        <div id="academics-1"></div>
                    </div>
                    <div class="card">
                        <h4 class="card-title">Comparison Plot of Marks</h4>
                        <div id="academics-2"></div>
                        
                    </div>
                    <div class="card">
                        <h4 class="card-title">Comparison Plot of Marks</h4>
                        <img class="card-img-top" src="plot_00.png" alt="Overall analysis plot">
                        
                    </div>
                </div>
                <div class="Academics-ovr">
                    <!-- <div class="card"> -->
                        
                        
                        <div class="c100 p92 big">
                    
                              <span>92%</span>
                            
                              <div class="slice">
                            
                                <div class="bar"></div>
                            
                                <div class="fill"></div>
                            
                              </div>
                            
                            </div>

                            
                        
                    <!-- </div> -->
                </div>
                <div class="Sports sub-container" id="sports-point" >
                    <div class="card">
                        <h4 class="card-title">Comparison Plot of Sports Participation</h4>
                        <div id="sports-1"></div>
                        
                    </div>
                </div>
                <div class="Sports-ovr">
                    <!-- <div class="card"> -->
                       
                        <div class="c100 p65 big orange">
                    
                            <span>65%</span>
                          
                            <div class="slice">
                          
                              <div class="bar"></div>
                          
                              <div class="fill"></div>
                          
                            </div>
                          
                          </div>

                          
                       
                    <!-- </div> -->
                </div>
                <div class="Technical sub-container" id="technical-point" >
                    <div class="card">
                        <h4 class="card-title">Scatter Plot of Hackathons and Internships</h4>
                        <div id="technical-1"></div>
                       
                    </div>
                    <div class="card">
                        <h4 class="card-title">Scatter Plot of Hackathons and Projects</h4>
                        <div id="technical-2"></div>
                       
                    </div>
                    <div class="card">
                        <h4 class="card-title">Projects</h4>
                        <div id="technical-3"></div>
                        
                    </div>
                </div>
                <div class="Technical-ovr">
                    <!-- <div class="card"> -->
                    
                        <div class="c100 p86 big green">
                    
                            <span>86%</span>
                          
                            <div class="slice">
                          
                              <div class="bar"></div>
                          
                              <div class="fill"></div>
                          
                            </div>
                          
                          </div>

                          
                        
                    <!-- </div> -->
                </div>
                <div class="Social sub-container" id="social-point" >
                    <div class="card">
                        <h4 class="card-title">Comparison plot of Social Work</h4>
                        <div id="social-1"></div>
                        
                    </div>
                </div>
                <div class="Social-ovr">
                    <!-- <div class="card"> -->
                        
                        <div class="c100 p72 big ">
                    
                            <span>72%</span>
                          
                            <div class="slice">
                          
                              <div class="bar"></div>
                          
                              <div class="fill"></div>
                          
                            </div>
                          
                          </div>

                        <div class="hidden" id="student0" data_student="{{ a }}" > </div>
                        <div class="hidden" id="student5" data_student="{{ b.company }}" > </div>
                        <div class="hidden" id="student6" data_student="{{ b.meandf2 }}" > </div>
                        <div class="hidden" id="student7" data_student="{{ b.maxdf2 }}" > </div>
                        <div class="hidden" id="student8" data_student="{{ b.scatter }}" > </div>
                        
                    <!-- </div> -->
                </div>
            </div>
        </section>
    </main>
</body>
</html>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="{% static 'IndustryFinder/main.js' %}"></script>